# Generated by Django 4.2.20 on 2025-03-16 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament_name', models.CharField(max_length=100)),
                ('frequency', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='Периодичность')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Продолжительность лечения (дни)')),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
