# Generated by Django 4.2.20 on 2025-03-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_permanent',
            field=models.BooleanField(default=False, verbose_name='Постоянное применение'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('user_id', 'medicament_name')},
        ),
    ]
