# Generated by Django 4.2.20 on 2025-03-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_schedule_is_permanent_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Укажите количество дней, если применение не постоянное.', null=True, verbose_name='Продолжительность лечения (дни)'),
        ),
    ]
